// AUTO-GENERATED by esbuild from src/*.ts via scripts/build-app.ts — do not edit directly.

"use strict";
(() => {
  // src/i18n.ts
  var SUPPORTED = ["en", "es", "ca"];
  var STORAGE_KEY = "fp_lang";
  function isSupportedLang(value) {
    return SUPPORTED.includes(value);
  }
  function detectDefaultLang() {
    const nav = (navigator.language || "en").toLowerCase();
    if (nav.startsWith("ca")) return "ca";
    if (nav.startsWith("es")) return "es";
    return "en";
  }
  var currentLang = detectDefaultLang();
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored && isSupportedLang(stored)) currentLang = stored;
  } catch {
  }
  function setLang(lang) {
    if (!isSupportedLang(lang)) return;
    currentLang = lang;
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch {
    }
    document.documentElement.lang = lang;
  }
  function getLang() {
    return currentLang;
  }
  function t(key) {
    const entry = window.I18N_STRINGS && window.I18N_STRINGS[key];
    if (!entry) return key;
    return entry[currentLang] || entry.en || key;
  }
  function localize(field) {
    if (!field) return "";
    return field[currentLang] || field.en || "";
  }
  document.documentElement.lang = currentLang;
  var FactpostorI18n = { setLang, getLang, t, localize, SUPPORTED_LANGS: SUPPORTED };
  window.FactpostorI18n = FactpostorI18n;
})();
