// AUTO-GENERATED by esbuild from src/*.ts via scripts/build-app.ts — do not edit directly.

"use strict";
(() => {
  // src/images.ts
  var WIKI_SUMMARY_BASE = "https://en.wikipedia.org/api/rest_v1/page/summary/";
  var CACHE_PREFIX = "fp_img_v1_";
  var memoryCache = {};
  function wikiUrlFor(title) {
    return WIKI_SUMMARY_BASE + encodeURIComponent(title.replace(/ /g, "_"));
  }
  async function fetchWikiImage(wikiTitle) {
    var _a, _b, _c, _d, _e;
    if (!wikiTitle) return null;
    if (Object.prototype.hasOwnProperty.call(memoryCache, wikiTitle)) {
      return (_a = memoryCache[wikiTitle]) != null ? _a : null;
    }
    const storageKey = CACHE_PREFIX + wikiTitle;
    try {
      const stored = localStorage.getItem(storageKey);
      if (stored !== null) {
        const parsed = stored === "" ? null : JSON.parse(stored);
        memoryCache[wikiTitle] = parsed;
        return parsed;
      }
    } catch {
    }
    let result = null;
    try {
      const res = await fetch(wikiUrlFor(wikiTitle));
      if (res.ok) {
        const data = await res.json();
        const imageUrl = ((_b = data.thumbnail) == null ? void 0 : _b.source) || ((_c = data.originalimage) == null ? void 0 : _c.source) || null;
        if (imageUrl) {
          const pageUrl = ((_e = (_d = data.content_urls) == null ? void 0 : _d.desktop) == null ? void 0 : _e.page) || "https://en.wikipedia.org/wiki/" + encodeURIComponent(wikiTitle.replace(/ /g, "_"));
          result = { imageUrl, pageUrl };
        }
      }
    } catch {
    }
    memoryCache[wikiTitle] = result;
    try {
      localStorage.setItem(storageKey, result ? JSON.stringify(result) : "");
    } catch {
    }
    return result;
  }
  function createPhotoElement(wikiTitle, altText, viewSourceText, unavailableText) {
    const wrapper = document.createElement("div");
    wrapper.className = "photo-card";
    const imgWrap = document.createElement("div");
    imgWrap.className = "photo-img-wrap loading";
    wrapper.appendChild(imgWrap);
    fetchWikiImage(wikiTitle).then((result) => {
      imgWrap.classList.remove("loading");
      if (result && result.imageUrl) {
        const img = document.createElement("img");
        img.src = result.imageUrl;
        img.alt = altText || "";
        img.loading = "lazy";
        img.onerror = () => {
          imgWrap.innerHTML = "\u{1F5BC}\uFE0F";
          imgWrap.classList.add("photo-fallback");
        };
        imgWrap.appendChild(img);
        const link = document.createElement("a");
        link.className = "photo-source-link";
        link.href = result.pageUrl;
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        link.textContent = viewSourceText || "View source";
        wrapper.appendChild(link);
      } else {
        imgWrap.textContent = "\u{1F5BC}\uFE0F";
        imgWrap.classList.add("photo-fallback");
        const label = document.createElement("div");
        label.className = "photo-unavailable-label";
        label.textContent = unavailableText || "Photo unavailable";
        wrapper.appendChild(label);
      }
    });
    return wrapper;
  }
  var FactpostorImages = { fetchWikiImage, createPhotoElement };
  window.FactpostorImages = FactpostorImages;
})();
