// AUTO-GENERATED by esbuild from src/*.ts via scripts/build-app.ts — do not edit directly.

"use strict";
(() => {
  // src/wiki.ts
  function isHttpsUrl(value) {
    if (typeof value !== "string") return false;
    try {
      return new URL(value).protocol === "https:";
    } catch {
      return false;
    }
  }
  function wikiPageUrl(title) {
    return "https://en.wikipedia.org/wiki/" + encodeURIComponent(title.replace(/ /g, "_"));
  }
  function parseWikiSummary(data, wikiTitle) {
    var _a, _b, _c, _d;
    const candidates = [(_a = data == null ? void 0 : data.thumbnail) == null ? void 0 : _a.source, (_b = data == null ? void 0 : data.originalimage) == null ? void 0 : _b.source];
    const imageUrl = candidates.find(isHttpsUrl);
    if (!imageUrl) return { status: "missing" };
    const page = (_d = (_c = data == null ? void 0 : data.content_urls) == null ? void 0 : _c.desktop) == null ? void 0 : _d.page;
    return { status: "found", result: { imageUrl, pageUrl: isHttpsUrl(page) ? page : wikiPageUrl(wikiTitle) } };
  }
  function lookupFromStatus(httpStatus) {
    return httpStatus === 404 ? { status: "missing" } : { status: "error" };
  }
  function parseCachedEntry(stored) {
    if (stored === null) return void 0;
    if (stored === "") return null;
    try {
      const parsed = JSON.parse(stored);
      if (parsed && isHttpsUrl(parsed.imageUrl) && isHttpsUrl(parsed.pageUrl)) {
        return { imageUrl: parsed.imageUrl, pageUrl: parsed.pageUrl };
      }
    } catch {
    }
    return void 0;
  }

  // src/images.ts
  var WIKI_SUMMARY_BASE = "https://en.wikipedia.org/api/rest_v1/page/summary/";
  var CACHE_PREFIX = "fp_img_v2_";
  var memoryCache = {};
  function wikiUrlFor(title) {
    return WIKI_SUMMARY_BASE + encodeURIComponent(title.replace(/ /g, "_"));
  }
  async function fetchWikiImage(wikiTitle) {
    var _a;
    if (!wikiTitle) return null;
    if (Object.prototype.hasOwnProperty.call(memoryCache, wikiTitle)) {
      return (_a = memoryCache[wikiTitle]) != null ? _a : null;
    }
    const storageKey = CACHE_PREFIX + wikiTitle;
    try {
      const cached = parseCachedEntry(localStorage.getItem(storageKey));
      if (cached !== void 0) {
        memoryCache[wikiTitle] = cached;
        return cached;
      }
    } catch {
    }
    let lookup = { status: "error" };
    try {
      const res = await fetch(wikiUrlFor(wikiTitle));
      lookup = res.ok ? parseWikiSummary(await res.json(), wikiTitle) : lookupFromStatus(res.status);
    } catch {
    }
    if (lookup.status === "error") return null;
    const result = lookup.status === "found" ? lookup.result : null;
    memoryCache[wikiTitle] = result;
    try {
      localStorage.setItem(storageKey, result ? JSON.stringify(result) : "");
    } catch {
    }
    return result;
  }
  function createPhotoElement(wikiTitle, altText, viewSourceText, unavailableText) {
    const wrapper = document.createElement("div");
    wrapper.className = "photo-card";
    const imgWrap = document.createElement("div");
    imgWrap.className = "photo-img-wrap loading";
    wrapper.appendChild(imgWrap);
    fetchWikiImage(wikiTitle).then((result) => {
      imgWrap.classList.remove("loading");
      if (result && result.imageUrl) {
        const img = document.createElement("img");
        img.src = result.imageUrl;
        img.alt = altText || "";
        img.loading = "lazy";
        img.onerror = () => {
          imgWrap.innerHTML = "\u{1F5BC}\uFE0F";
          imgWrap.classList.add("photo-fallback");
        };
        imgWrap.appendChild(img);
        const link = document.createElement("a");
        link.className = "photo-source-link";
        link.href = result.pageUrl;
        link.target = "_blank";
        link.rel = "noopener noreferrer";
        link.textContent = viewSourceText || "View source";
        wrapper.appendChild(link);
      } else {
        imgWrap.textContent = "\u{1F5BC}\uFE0F";
        imgWrap.classList.add("photo-fallback");
        const label = document.createElement("div");
        label.className = "photo-unavailable-label";
        label.textContent = unavailableText || "Photo unavailable";
        wrapper.appendChild(label);
      }
    });
    return wrapper;
  }
  var FactpostorImages = { fetchWikiImage, createPhotoElement };
  window.FactpostorImages = FactpostorImages;
})();
