// Curated fact database - Large collection of interesting facts
const FACTS = [
    "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
    "Honey never spoils. Edible honey has been found in 3,000-year-old Egyptian tombs.",
    "A group of flamingos is called a flamboyance.",
    "Nintendo was founded in 1889 as a playing card company.",
    "Sharks are older than trees. Sharks appeared around 450 million years ago; trees around 350 million years ago.",
    "Octopuses have three hearts and blue blood.",
    "The shortest war in history lasted 38 minutes between Britain and Zanzibar in 1896.",
    "Bananas are berries, but strawberries aren't.",
    "A day on Venus is longer than a year on Venus.",
    "The unicorn is the national animal of Scotland.",
    "Oxford University is older than the Aztec Empire.",
    "There are more possible iterations of a game of chess than there are atoms in the known universe.",
    "Carrots were originally purple before the 17th century when Dutch growers cultivated orange carrots.",
    "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
    "A single strand of spaghetti is called a spaghetto.",
    "The hashtag symbol is technically called an octothorpe.",
    "Cows have best friends and get stressed when they are separated.",
    "The fingerprints of koalas are so similar to humans that they have been confused at crime scenes.",
    "A group of owls is called a parliament.",
    "The inventor of the Pringles can is now buried in one.",
    "Sea otters hold hands when they sleep to keep from drifting apart.",
    "The longest English word without a vowel is rhythms.",
    "An ostrich's eye is bigger than its brain.",
    "Wombat poop is cube-shaped.",
    "The inventor of the frisbee was turned into a frisbee after he died, with his ashes being molded into discs.",
    "Pigeons can do math as well as monkeys.",
    "A jiffy is an actual unit of time: 1/100th of a second.",
    "The dot over the letter 'i' is called a tittle.",
    "Maine is the closest U.S. state to Africa.",
    "The voice actors for Mickey and Minnie Mouse were married in real life.",
    "In Switzerland, it is illegal to own just one guinea pig because they get lonely.",
    "The woolly mammoth was still around when the Great Pyramid was being built.",
    "There are more stars in space than grains of sand on every beach on Earth.",
    "A group of pugs is called a grumble.",
    "The King of Hearts is the only king in a deck of cards without a mustache.",
    "Armadillos are the only animals besides humans that can contract leprosy.",
    "A crocodile cannot stick its tongue out.",
    "Alaska is simultaneously the most northern, western, and eastern state in the U.S.",
    "The lighter was invented before the match.",
    "A bolt of lightning contains enough energy to toast 100,000 slices of bread.",
    "Dolphins have names for each other and can call out to specific individuals.",
    "The world's oldest known recipe is for beer.",
    "A blue whale's heart is so large that a human could swim through its arteries.",
    "The average person walks the equivalent of three times around the world in their lifetime.",
    "Bees can recognize human faces.",
    "The longest hiccupping spree lasted 68 years.",
    "There is enough gold in Earth's core to coat the entire surface in 1.5 feet of gold.",
    "A snail can sleep for three years.",
    "The probability of shuffling a deck of cards into a sequence that has never existed is essentially 100%.",
    "Hot water freezes faster than cold water under certain conditions, known as the Mpemba effect.",
    "Sloths can hold their breath longer than dolphins can.",
    "The Hawaiian alphabet only has 12 letters.",
    "A shrimp's heart is located in its head.",
    "Dead people can get goosebumps.",
    "The Twitter bird's official name is Larry.",
    "A single cloud can weigh more than 1 million pounds.",
    "The human nose can detect over 1 trillion different scents.",
    "Butterflies taste with their feet.",
    "The average person spends 6 months of their lifetime waiting for red lights to turn green.",
    "A group of crows is called a murder.",
    "Polar bears have black skin under their white fur.",
    "The Great Wall of China is not visible from space with the naked eye.",
    "Cats have fewer toes on their back paws than their front paws.",
    "The longest wedding veil was longer than 63 football fields.",
    "You can't hum while holding your nose closed.",
    "A group of jellyfish is called a smack.",
    "The average cloud weighs about 1.1 million pounds.",
    "Rats laugh when they are tickled.",
    "The average person will spend 25 years asleep in their lifetime.",
    "McDonald's sells 75 hamburgers every second of every day.",
    "A group of ferrets is called a business.",
    "The human body contains enough fat to make seven bars of soap.",
    "A group of rhinoceroses is called a crash.",
    "Tigers have striped skin, not just striped fur.",
    "Pearls melt in vinegar.",
    "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo'.",
    "A group of zebras is called a dazzle.",
    "Apples are more effective at waking you up in the morning than coffee.",
    "The moon has moonquakes.",
    "A group of parrots is called a pandemonium.",
    "Babies have 94 more bones than adults.",
    "The tooth is the only part of the human body that cannot heal itself.",
    "A cockroach can live for several weeks without its head.",
    "Scotland has 421 words for snow.",
    "Peanuts are not nuts; they are legumes.",
    "A group of hippos is called a bloat.",
    "The shortest complete sentence in English is 'I am.'",
    "A group of larks is called an exaltation.",
    "Venus is the only planet that spins clockwise.",
    "The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
    "A duck's quack doesn't echo, and no one knows why.",
    "The first oranges weren't orange; they were green.",
    "Horses cannot vomit or breathe through their mouths.",
    "A group of ravens is called an unkindness.",
    "The longest time between two twins being born is 87 days.",
    "Every human spent about half an hour as a single cell.",
    "The blob of toothpaste on a toothbrush is called a nurdle.",
    "Cows kill more people than sharks do every year.",
    "The inventor of the Taser named it after a book series: Tom Swift and His Electric Rifle.",
    "A group of porcupines is called a prickle.",
    "Strawberries have more vitamin C than oranges.",
    "The chances of you dying on the way to get lottery tickets is higher than your chances of winning.",
    "Humans are the only animals that blush.",
    "A group of geese on the ground is called a gaggle, but in flight, it's called a skein.",
    "The name 'Jessica' was created by Shakespeare for his play Merchant of Venice.",
    "Tennis was originally played with bare hands.",
    "A group of lemurs is called a conspiracy.",
    "Casu Marzu is a Sardinian cheese that contains live maggots and is considered a delicacy.",
    "All the ants on Earth weigh about as much as all the humans.",
    "A sneeze travels out of your mouth at over 100 miles per hour.",
    "The longest English word is 189,819 letters long and would take three and a half hours to pronounce.",
    "A group of butterflies is called a kaleidoscope.",
    "The electric chair was invented by a dentist.",
    "You cannot snore and dream at the same time.",
    "Human teeth are just as strong as shark teeth.",
    "Your brain uses 20% of the total oxygen and blood in your body.",
    "A group of kangaroos is called a mob.",
    "Humans share 50% of their DNA with bananas.",
    "The longest recorded flight of a chicken is 13 seconds.",
    "A group of cats is called a clowder.",
    "A blue whale's tongue weighs as much as an elephant.",
    "It would take 19 minutes to fall to the center of the Earth.",
    "The longest place name on the planet is 85 letters long.",
    "A group of eagles is called a convocation.",
    "It is impossible for most people to lick their own elbow.",
    "An 11-year-old girl invented the phrase 'the Internet' in 1996.",
    "Your body gives off enough heat in 30 minutes to bring half a gallon of water to a boil.",
    "The average person walks past 36 murderers in their lifetime.",
    "The world's oldest piece of chewing gum is over 9,000 years old.",
    "A group of frogs is called an army.",
    "The inventor of the microwave only received $2 for his discovery.",
    "Your eyes stay the same size from birth, but your nose and ears never stop growing.",
    "A group of lobsters is called a risk.",
    "The cigarette lighter was invented before the match.",
    "If you keep a goldfish in a dark room, it will eventually turn white.",
    "Dolphins sleep with one eye open.",
    "A group of giraffe is called a tower.",
    "The average person spends two weeks of their life kissing.",
    "Sea horses are monogamous and mate for life.",
    "A group of hedgehogs is called a prickle.",
    "Russia has a larger surface area than Pluto.",
    "French was the official language of England for over 600 years.",
    "A group of gorillas is called a band.",
    "The wood frog can hold its pee for up to eight months.",
    "Antarctica is the largest desert in the world.",
    "A group of sharks is called a shiver.",
    "More people are killed each year by vending machines than by sharks.",
    "A group of squirrels is called a scurry.",
    "The longest anyone has ever gone without sleep is 11 days.",
    "A group of ants is called a colony.",
    "Pigs cannot look up at the sky.",
    "The sum of all the numbers on a roulette wheel is 666.",
    "A group of peacocks is called an ostentation.",
    "The first computer virus was created in 1983.",
    "A group of foxes is called a skulk.",
    "It is physically impossible for pigs to look up into the sky.",
    "The loudest animal on Earth is the sperm whale.",
    "A group of toads is called a knot.",
    "Baby carrots are just regular carrots cut and shaped into smaller pieces.",
    "The original name for the search engine Google was Backrub.",
    "A group of wolves is called a pack.",
    "Water makes different pouring sounds depending on its temperature.",
    "The most expensive pizza in the world costs $12,000 and takes 72 hours to make.",
    "A group of snakes is called a den.",
    "Humans are the only animals that cry emotional tears."
];

// Export for use in app.js
window.FACTS = FACTS;
