#!/usr/bin/env -S npx tsx
// Bundles the TypeScript sources under src/ into the plain <script> files
// index.html loads directly, so the deployed site stays a build-free static
// page (no bundler/module resolution needed in the browser).
//
// Usage: npm run build:app

import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const banner = '// AUTO-GENERATED by esbuild from src/*.ts via scripts/build-app.ts — do not edit directly.\n';

const entries: Array<{ entry: string; outfile: string }> = [
    { entry: 'src/i18n.ts', outfile: 'js/i18n.js' },
    { entry: 'src/images.ts', outfile: 'js/images.js' },
    { entry: 'src/app.ts', outfile: 'app.js' }
];

for (const { entry, outfile } of entries) {
    await build({
        entryPoints: [join(root, entry)],
        outfile: join(root, outfile),
        bundle: true,
        format: 'iife',
        target: 'es2019',
        banner: { js: banner }
    });
    console.log(`Built ${outfile} from ${entry}`);
}
