#!/usr/bin/env node
// Merges the human-edited JSON in data/ into a single browser-loadable script
// (js/data.bundle.js) that sets plain window globals. We do this instead of
// fetch()-ing the JSON at runtime so the game still works when index.html is
// opened directly from disk (file://), where fetch() of local files is blocked.
//
// Usage: node scripts/build-data.mjs
// Run this after editing anything under data/.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const dataDir = join(root, 'data');

function readJson(name) {
    const path = join(dataDir, name);
    if (!existsSync(path)) {
        throw new Error(`Missing required data file: data/${name}`);
    }
    const raw = readFileSync(path, 'utf-8');
    try {
        return JSON.parse(raw);
    } catch (e) {
        throw new Error(`Invalid JSON in data/${name}: ${e.message}`);
    }
}

const i18n = readJson('i18n.json');
const categories = readJson('categories.json');
const classicWords = readJson('classic-words.json');
const famousPeople = readJson('famous-people.json');
const facts = readJson('facts.json');

function assertArray(name, value, minLength) {
    if (!Array.isArray(value)) throw new Error(`${name} must be a JSON array`);
    if (value.length < minLength) {
        throw new Error(`${name} has only ${value.length} items, expected at least ${minLength}`);
    }
}

assertArray('classic-words.json', classicWords, 100);
assertArray('famous-people.json', famousPeople, 100);
assertArray('facts.json', facts, 100);

const seenIds = new Set();
for (const [file, arr] of [['classic-words.json', classicWords], ['famous-people.json', famousPeople], ['facts.json', facts]]) {
    const idsInFile = new Set();
    for (const item of arr) {
        if (!item.id) throw new Error(`Item missing id in ${file}: ${JSON.stringify(item).slice(0, 120)}`);
        if (idsInFile.has(item.id)) throw new Error(`Duplicate id "${item.id}" within ${file}`);
        idsInFile.add(item.id);
    }
}

const banner = `// AUTO-GENERATED by scripts/build-data.mjs from data/*.json — do not edit directly.\n// Edit the JSON files in data/ and re-run: node scripts/build-data.mjs\n`;

const output = banner +
    `window.I18N_STRINGS = ${JSON.stringify(i18n)};\n` +
    `window.CATEGORIES = ${JSON.stringify(categories)};\n` +
    `window.CLASSIC_WORDS = ${JSON.stringify(classicWords)};\n` +
    `window.FAMOUS_PEOPLE = ${JSON.stringify(famousPeople)};\n` +
    `window.FACTS_DATA = ${JSON.stringify(facts)};\n`;

writeFileSync(join(root, 'js', 'data.bundle.js'), output);

console.log(`Built js/data.bundle.js`);
console.log(`  classic-words: ${classicWords.length} items`);
console.log(`  famous-people: ${famousPeople.length} items`);
console.log(`  facts: ${facts.length} items`);
